{
 "title": "iota-core Local Metrics",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "NodeID", "label": "Node Identity", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synced",
   "type": "stat",
   "description": "Describes if the node is in synced state.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_sync_status{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total BPS",
   "type": "stat",
   "description": "Aggregated BPS for all block types in the communication layer.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(tangle_booked_blocks_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Total BPS"
    }
   ]
  },
  {
   "title": "Total Database Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_size_bytes_permanent{instance=~\"$instance\"} /1024/1024 + db_size_bytes_prunable{instance=~\"$instance\"} /1024/1024"
    }
   ]
  },
  {
   "title": "Permanent DB Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_size_bytes_permanent{instance=~\"$instance\"}) /1024/1024"
    }
   ]
  },
  {
   "title": "Prunable DB size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_size_bytes_prunable{instance=~\"$instance\"} /1024/1024"
    }
   ]
  },
  {
   "title": "Active chains ",
   "type": "stat",
   "description": "Number of currently tracked commitment chains",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "commitments_active_chains_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Seen chains",
   "type": "stat",
   "description": "Number of  commitment chains seen by the node since it started.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "commitments_seen_chains_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Spawned engines",
   "type": "stat",
   "description": "Number of  engines spawned by the node since it started (including the original main engine).",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "commitments_spawned_engines_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Engine switches",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "commitments_forks_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "BPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Block Per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "BPS" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_booked_blocks_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Block Per Second {{block_type}}"
    }
   ]
  },
  {
   "title": "Online Commitee Seats",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "account_active_seats{instance=~\"$instance\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "graph",
   "description": "Shows tips in block and value layer.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_strong_tips_count{instance=~\"$instance\"}",
     "legendFormat": "Strong Tips"
    },
    {
     "expr": "tangle_weak_tips_count{instance=~\"$instance\"}",
     "legendFormat": "Weak Tips"
    }
   ]
  },
  {
   "title": "Solidifier-requested blocks total",
   "type": "graph",
   "description": "Number of blocks requested through solidification. ",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_missing_blocks_total{instance=~\"$instance\"}",
     "legendFormat": "Solidifier-requested blocks"
    }
   ]
  },
  {
   "title": "Solidifier-requested blocks per second",
   "type": "graph",
   "description": "Number of blocks requested through solidification. ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_missing_blocks_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Solidifier-requested blocks"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "graph",
   "description": "Number of blocks in missingBlockStore. These are the block the node knows it doesn't have and tries to requests them.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_missing_blocks_total{instance=~\"$instance\"}",
     "legendFormat": "Missing Blocks"
    }
   ]
  },
  { "title": "OTV metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total number of conflicts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conflict_created_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of finalized conflicts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conflict_resolved_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of confirmed conflicts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conflict_resolved_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total number of unresolved conflicts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conflict_created_total{instance=~\"$instance\"} - conflict_resolved_total{instance=~\"$instance\"}"
    }
   ]
  }
 ]
}