#
# node-docker-setup __VERSION__
# https://github.com/iotaledger/node-docker-setup
#

services:

##################################################################
#  iota-core                                                     #
##################################################################

  iota-core:
    container_name: iota-core
    image: iotaledger/iota-core:1.0-beta
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    depends_on:
      traefik:
        condition: service_started
    ports:
      - "15600:15600/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iota-core.service=iota-core"
      - "traefik.http.routers.iota-core.rule=Host(`${NODE_HOST:-localhost}`)"
      - "traefik.http.routers.iota-core.entrypoints=web"
      - "traefik.http.services.iota-core.loadbalancer.server.port=14265"
      - "traefik.http.routers.iota-core.middlewares=redirect-dashboard"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.regex=^(https?://[^/]+)/?$$"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.replacement=$$1/dashboard/"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.permanent=true"
    cap_drop:
      - ALL
    volumes:
      - ./${IOTA_CORE_CONFIG_FILE:-config.json}:/app/config.json:ro
      - ./peering.json:/app/peering.json
      - ./data:/app/data
    command: >
      -c config.json
      --p2p.bindMultiAddresses=/ip4/0.0.0.0/tcp/15600,/ip6/::/tcp/15600
      --p2p.identityPrivateKeyFilePath=data/p2p/identity.key
      --p2p.autopeering.externalMultiAddresses=${EXTERNAL_P2P_MULTIADDRESS:-}
      --profiling.bindAddress=iota-core:6060
      --debugAPI.db.path=data/debug
      --db.path=data/database
      --protocol.snapshot.path=data/snapshots/snapshot.bin
      --protocol.protocolParametersPath=data/protocol_parameters.json
      --prometheus.enabled=true
      --prometheus.bindAddress=iota-core:9311
      --inx.enabled=true
      --inx.bindAddress=iota-core:9029

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    container_name: traefik
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "${HTTP_PORT:-80}:80/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"

##################################################################
#  Monitoring                                                    #
##################################################################

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "65532"
    volumes:
      - ./data/prometheus/:/prometheus
      - ./assets/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    profiles:
      - monitoring

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    command: 
      - --housekeeping_interval=30s    # kubernetes default args
      - --max_housekeeping_interval=35s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --store_container_labels=false
      - --global_housekeeping_interval=30s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --disable_metrics=accelerator,advtcp,cpu_topology,disk,hugetlb,memory_numa,percpu,referenced_memory,resctrl,sched,tcp,udp
      - --enable_load_reader=true
      - --docker_only=true          # only show stats for docker containers
      - --allow_dynamic_housekeeping=true
      - --storage_duration=1m0s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    profiles:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "65532"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${NODE_HOST:-localhost}`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=${NODE_HOST:-localhost}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/local_dashboard.json
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./assets/grafana/:/etc/grafana/provisioning/
    profiles:
      - monitoring

##################################################################
#  INX Extensions                                                #
#  disable them out by commenting out the services               #
##################################################################

  inx-indexer:
    container_name: inx-indexer
    image: iotaledger/inx-indexer:2.0-beta
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
    volumes:
      - ./data:/app/database
    command: >
      --inx.address=iota-core:9029
      --indexer.db.sqlite.path=database/indexer
      --restAPI.bindAddress=inx-indexer:9091
      --prometheus.enabled=true
      --prometheus.bindAddress=inx-indexer:9312

  inx-mqtt:
    container_name: inx-mqtt
    image: iotaledger/inx-mqtt:2.0-beta
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
    command: >
      --inx.address=iota-core:9029
      --mqtt.websocket.bindAddress=inx-mqtt:1888
      --prometheus.enabled=true
      --prometheus.bindAddress=inx-mqtt:9312

  inx-dashboard:
    container_name: inx-dashboard
    image: iotaledger/inx-dashboard:2.0-beta
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iota-core-dashboard.service=iota-core-dashboard"
      - "traefik.http.routers.iota-core-dashboard.rule=Host(`${NODE_HOST:-localhost}`) && (Path(`/dashboard`) || PathPrefix(`/dashboard/`))"
      - "traefik.http.routers.iota-core-dashboard.entrypoints=web"
      - "traefik.http.services.iota-core-dashboard.loadbalancer.server.port=8081"
    volumes:
      - ./data/dashboard:/app/dashboard
    command: >
      --inx.address=iota-core:9029
      --dashboard.bindAddress=inx-dashboard:8081
      --dashboard.auth.identityFilePath=/app/dashboard/identity.key
      --dashboard.auth.username=${DASHBOARD_USERNAME:-admin}
      --dashboard.auth.passwordHash=${DASHBOARD_PASSWORD:-0000000000000000000000000000000000000000000000000000000000000000}
      --dashboard.auth.passwordSalt=${DASHBOARD_SALT:-0000000000000000000000000000000000000000000000000000000000000000}
      --prometheus.enabled=true
      --prometheus.bindAddress=inx-dashboard:9312

  inx-blockissuer:
    container_name: inx-blockissuer
    image: iotaledger/inx-blockissuer:1.0-beta
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    environment:
      - "BLOCKISSUER_PRV_KEY=${BLOCKISSUER_PRV_KEY:-}"
    command: >
      --inx.address=iota-core:9029
      --restAPI.bindAddress=inx-blockissuer:9086
      --blockIssuer.accountAddress=${BLOCKISSUER_ACCOUNT_ADDR:-}
      --blockIssuer.proofOfWork.targetTrailingZeros=25
    profiles:
      - blockissuer

  inx-validator:
    container_name: inx-validator
    image: iotaledger/inx-validator:1.0-beta
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_started
    environment:
      - "VALIDATOR_PRV_KEY=${VALIDATOR_PRV_KEY:-}"
    command: >
      --inx.address=iota-core:9029
      --validator.accountAddress=${VALIDATOR_ACCOUNT_ADDR:-}
    profiles:
      - validator
