#
# node-docker-setup __VERSION__
# https://github.com/iotaledger/node-docker-setup
#

services:

##################################################################
#  IOTA-CORE                                                     #
##################################################################

  iota-core:
    labels:
      - "traefik.http.routers.iota-core.entrypoints=websecure"
      - "traefik.http.routers.iota-core.tls=true"
      - "traefik.http.routers.iota-core.tls.certresolver=myresolver"

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443/tcp"

##################################################################
#  Monitoring                                                    #
##################################################################

  grafana:
    labels:
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"

##################################################################
#  INX Extensions                                                #
#  disable them out by commenting out the services               #
##################################################################

  inx-dashboard:
    labels:
      - "traefik.http.routers.iota-core-dashboard.entrypoints=websecure"
      - "traefik.http.routers.iota-core-dashboard.tls=true"
