{
 "title": "Node Dashboard Legacy",
 "description": "Dashboard for the IOTA node software",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "peers",
    "query": {
     "query": "label_values(iota_peers_all_transactions,address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Node Version",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_info_app", "legendFormat": "{{version}}" }
   ]
  },
  {
   "type": "stat",
   "description": "The sync status of the node",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(iota_info_latest_milestone_index - on () iota_info_latest_solid_milestone_index)"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "stat",
   "description": "Amount of tips per second",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_info_tips{}", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the node",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time()-container_start_time_seconds{name=\"hornet\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "CPU usage",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"hornet\"}[5m]))/sum(machine_cpu_cores)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "RAM usage",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"hornet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "Size of the database",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_data_sizes_bytes{}" }
   ]
  },
  {
   "title": "Neighbors",
   "type": "stat",
   "description": "Neighbors count",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_peers_connected{}" }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "description": "CPU usage of every single container running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) / scalar(machine_cpu_cores) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "timeseries",
   "description": "Memory usage of every single container running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "Size of the databases",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "iota_data_sizes_bytes{}", "legendFormat": "Tangle" }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Messages per second per peer",
   "type": "timeseries",
   "description": "MPS per peer per type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(iota_peers_all_transactions{address=~\"$peers\"}[1m])",
     "legendFormat": "{{id}} - {{type}}"
    }
   ]
  },
  {
   "title": "Requests per second per peer",
   "type": "timeseries",
   "description": "Requests per second per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (id) (rate(iota_peers_received_transaction_requests{address=~\"$peers\"}[1m]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Sent heartbeats per peer",
   "type": "timeseries",
   "description": "Distribution of sent heartbeats per peer",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(iota_peers_sent_heartbeats{address=~\"$peers\"}[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Received heartbeats per peer",
   "type": "timeseries",
   "description": "Distribution of received heartbeats per peer",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(iota_peers_received_heartbeats{address=~\"$peers\"}[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Dropped packages per peer",
   "type": "timeseries",
   "description": "Distribution of dropped packages per peer",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(iota_peers_dropped_sent_packets{address=~\"$peers\"}[1m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Traefik requests ( Success + / Error - )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{service=\"hornet@docker\"}[1m])",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}